### ISSUE TITLE
Cat Cafe

### ISSUE THREAD

**Issue by paigeheff** [paigeheff/confectionery-website-prototype#1]
<img width="1346" alt="screenshot 2016-12-05 10 44 32" src="https://cloud.githubusercontent.com/assets/22118348/20891378/5c729b60-bad8-11e6-8b12-7128fd14c686.png">

I am working on my restaurant, and it keeps saying the p is supposed to come before the classes .mostpopular, .coffeelist etc, but whenever I move them around, it still says it needs to be moved to before the p selector.

Where would I put them? I don't really get it.

**Comment by paigeheff** [comment]
@thomasjbradley

**Comment by paigeheff** [comment]
<img width="757" alt="screenshot 2016-12-05 11 40 07" src="https://cloud.githubusercontent.com/assets/22118348/20893402/a27fa7a4-badf-11e6-9123-7a306a1fd8c0.png">

I am trying to get the images to go to the left beside the text, but it keeps coming out in a sort of ladder formation.. Like one is further in than the other image. How do I fix this,
I have tried margins, padding, etc and nothing is working. 

Is the website looking like it's coming along okay?

@thomasjbradley

Also, when I try to use margins on the button, it never works, it shows it when I inspect the element but it doesn't move at all.

It is also saying that I need to have the "timedate" in the time selector, but I am not sure how I would write it because when I do it, it says its incorrect.

**Comment by thomasjbradley** [comment]
What is the `.hours h2, p` trying to target?
The `<p>` and `<h2>` inside of `.hours`?

Right now it's targeting the `<h2>` inside `.hours` and *every single* `<p>` on the website.

**Comment by thomasjbradley** [comment]
Those images are floating, correct? Does their parent element need something on it?

**Comment by thomasjbradley** [comment]
Time: https://learn-the-web.algonquindesign.ca/topics/html-semantics/#more-specific-elements

**Comment by paigeheff** [comment]
Yes, I'm trying to target the h2 and p inside of .hours.

I don't have the images as a float, I just have a border around them. But when I do float them, they go all weird. What do you mean by that? How would I get them to just go in  a straight line up and down?

**Comment by paigeheff** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
To get the `<p>` inside of `.hours` you’d need to write this:

```css
.hours h2,
.hours p {

}
```

*Notice how `.hours` is written twice.*

**Comment by thomasjbradley** [comment]
The images are floating, I can see it here in the CSS:
https://github.com/paigeheff/confectionery-website-prototype/blob/gh-pages/css/main.css#L265

Since the images are floated, do their parent elements need a specific CSS property on them to remind them that there are floated things inside? Remind them to wrap around those floated things?

**Comment by paigeheff** [comment]
overflow:hidden :) thank you!

**Comment by thomasjbradley** [comment]
Good work!
