### ISSUE TITLE
38em

### ISSUE THREAD

**Issue by paigeheff** [paigeheff/confectionery-website-prototype#2]
<img width="1229" alt="screenshot 2016-12-07 17 23 40" src="https://cloud.githubusercontent.com/assets/22118348/20989264/1290226c-bca2-11e6-9669-c5878dc4a1c5.png">

I am trying to get the names in a row but they keep getting distorted, and I did the code like the exercise we did, and it's still not working. Am I missing something?

@thomasjbradley

**Comment by paigeheff** [comment]
I am also trying to get the quote to be in a border,  but it's going into the picture beside it. I tried putting  a margin on .border p and .review p and nothing worked. 
also, how do I get the picture so it's not going into the footer at the very bottom?
<img width="1094" alt="screenshot 2016-12-07 17 32 45" src="https://cloud.githubusercontent.com/assets/22118348/20989601/46e209f8-bca3-11e6-825f-d4fa76c953f7.png">


@thomasjbradley

**Comment by thomasjbradley** [comment]
For the names, I don't exactly know what layout you want, but I'd guess that you need to turn `float` off in the `38em` media query.

**Comment by thomasjbradley** [comment]
For the quote: have you tried floating in too?

For the footer: you already know the answer to that one… 😉

**Comment by paigeheff** [comment]
I got the footer :) 

and I fixed the quote!

**Comment by paigeheff** [comment]
<img width="903" alt="screenshot 2016-12-08 13 54 27" src="https://cloud.githubusercontent.com/assets/22118348/21023298/e2abf2c2-bd4d-11e6-9428-929f37659345.png">

I don't really understand why it is saying that it's not changing when it hovers, because I can see the navigation list changing colours in my browser. Is there something I should change?


also, 
<img width="639" alt="screenshot 2016-12-08 13 58 54" src="https://cloud.githubusercontent.com/assets/22118348/21023424/781992c4-bd4e-11e6-9281-2630f20fbc13.png">

Does the list look weird this way? Should I change anything to make it look better?
Like the spacing or something?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Commit and sync please—I can't see the navigation highlighting.

**Comment by thomasjbradley** [comment]
Yeah, a little weird. Maybe try left-aligned.
Also try to make the text the same number of words so they are approximately the same height.

**Comment by paigeheff** [comment]
I synced it. 

OKay I will try that!

**Comment by paigeheff** [comment]
Can you see the background when it hovers?

**Comment by thomasjbradley** [comment]
Yep I can see the background colour now.

The problem that Markbot is running into is that the `<a>` tag’s background isn’t changing, in your code it’s the `<li>` tag’s background that changes.

**Comment by paigeheff** [comment]
perfect got it!
